version: '3.7'

services:

#  authdemo:
#    build:
#      context: .
#    container_name: authdemo
#    restart: on-failure
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
#      SPRING_DATASOURCE_USERNAME: ${DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - postgres

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5442:5432'
    volumes:
      - ./.app-init/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pd_data:/var/lib/postgresql/data

# Volumes
volumes:
  data:
    driver: local
  pd_data:
    driver: local